/* Monroe Lab – full-text ranked search (issue #188)
 *
 * Loads docs/search-index.json (generated by scripts/build-object-index.py:
 * every .md under docs/ with frontmatter + base64 images stripped) lazily on
 * first query, then ranks documents against a multi-word query:
 *   - all words must match somewhere in title or body (AND)
 *   - title matches score far above heading matches, which score above
 *     plain body occurrences; exact/prefix title matches rank highest
 *   - the full query as a phrase earns a bonus in title or body
 * Results carry a highlighted snippet around the first body match.
 *
 * API (window.Lab.search):
 *   query(q, opts) -> Promise<[{path, title, type, score, snippet}]>
 *     opts.paths  — Set of allowed paths (with or without .md) to restrict to
 *     opts.types  — Set of allowed type strings
 *     opts.limit  — max results (default 50)
 *   load() -> Promise  — prefetch the index (optional warm-up)
 */
(function() {
  'use strict';

  var _index = null;
  var _promise = null;

  function load() {
    if (_index) return Promise.resolve(_index);
    if (_promise) return _promise;
    var base = (window.Lab && window.Lab.BASE) || '/lab-handbook/';
    _promise = fetch(base + 'search-index.json')
      .then(function(resp) { return resp.ok ? resp.json() : []; })
      .catch(function() { return []; })
      .then(function(rows) {
        rows.forEach(function(r) {
          r._ltitle = (r.title || '').toLowerCase();
          r._ltext = (r.text || '').toLowerCase();
          // Headings only, for mid-tier scoring
          var heads = [];
          (r.text || '').split('\n').forEach(function(line) {
            if (line.charAt(0) === '#') heads.push(line.replace(/^#+\s*/, ''));
          });
          r._lheads = heads.join('\n').toLowerCase();
        });
        _index = rows;
        return rows;
      });
    return _promise;
  }

  function countOccurrences(haystack, needle) {
    var count = 0, pos = 0;
    while (count < 10) {
      pos = haystack.indexOf(needle, pos);
      if (pos === -1) break;
      count++;
      pos += needle.length;
    }
    return count;
  }

  function scoreRow(row, words, phrase) {
    var score = 0;
    for (var i = 0; i < words.length; i++) {
      var w = words[i];
      var inTitle = row._ltitle.indexOf(w) !== -1;
      var bodyCount = countOccurrences(row._ltext, w);
      if (!inTitle && !bodyCount) return 0; // AND across words

      if (inTitle) {
        if (row._ltitle === w) score += 100;
        else if (row._ltitle.indexOf(w) === 0) score += 60;
        else score += 35;
      }
      if (row._lheads && row._lheads.indexOf(w) !== -1) score += 15;
      score += Math.min(bodyCount, 10) * 3;
    }
    if (words.length > 1) {
      if (row._ltitle.indexOf(phrase) !== -1) score += 80;
      else if (row._ltext.indexOf(phrase) !== -1) score += 25;
    }
    return score;
  }

  function esc(s) {
    return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
  }

  // HTML snippet around the first match of any query word, matches <mark>ed.
  function makeSnippet(row, words, phrase) {
    var text = row.text || '';
    var ltext = row._ltext;
    var pos = -1, matchLen = 0;
    if (words.length > 1) {
      pos = ltext.indexOf(phrase);
      matchLen = phrase.length;
    }
    if (pos === -1) {
      for (var i = 0; i < words.length; i++) {
        var p = ltext.indexOf(words[i]);
        if (p !== -1 && (pos === -1 || p < pos)) { pos = p; matchLen = words[i].length; }
      }
    }
    if (pos === -1) return '';

    var start = Math.max(0, pos - 70);
    var end = Math.min(text.length, pos + matchLen + 110);
    // Snap to word boundaries
    if (start > 0) { var sp = text.indexOf(' ', start); if (sp !== -1 && sp < pos) start = sp + 1; }
    var raw = text.slice(start, end).replace(/\s+/g, ' ');

    // Single-pass mark with all words as one alternation (longest first) so
    // overlapping words never produce nested <mark> tags.
    var alts = words.slice().sort(function(a, b) { return b.length - a.length; })
      .map(function(w) { return w.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); });
    var re = new RegExp('(' + alts.join('|') + ')', 'gi');
    var html = esc(raw).replace(re, '<mark>$1</mark>');

    return (start > 0 ? '… ' : '') + html + (end < text.length ? ' …' : '');
  }

  function normPath(p) { return p.replace(/\.md$/, ''); }

  async function query(q, opts) {
    opts = opts || {};
    var phrase = (q || '').toLowerCase().trim();
    var words = phrase.split(/\s+/).filter(Boolean);
    if (!words.length) return [];

    var rows = await load();
    var allowedPaths = null;
    if (opts.paths) {
      allowedPaths = new Set();
      opts.paths.forEach(function(p) { allowedPaths.add(normPath(p)); });
    }

    var results = [];
    for (var i = 0; i < rows.length; i++) {
      var row = rows[i];
      if (allowedPaths && !allowedPaths.has(normPath(row.path))) continue;
      if (opts.types && opts.types.size && !opts.types.has(row.type || '_untyped')) continue;
      var score = scoreRow(row, words, phrase);
      if (!score) continue;
      results.push({
        path: row.path,
        title: row.title,
        type: row.type,
        score: score,
        snippet: makeSnippet(row, words, phrase),
      });
    }
    results.sort(function(a, b) { return b.score - a.score || a.title.localeCompare(b.title); });
    return results.slice(0, opts.limit || 50);
  }

  window.Lab = window.Lab || {};
  window.Lab.search = { load: load, query: query };
})();
